import { PatternConfig } from "@/types"
import { HeroContent } from "@/components/playground/HeroPrototype"

export function generateFullSection(patternName: string, config: PatternConfig, content: HeroContent): string {
  const componentName = patternName.replace(/\s/g, "")
  return `"use client"

// Complete hero section — generated by bglab.dev
// 1. Copy ${componentName}.tsx into /components/patterns/
// 2. Paste this file into your page or as a separate HeroSection component

import { ${componentName} } from "@/components/patterns/${componentName}"

export function HeroSection() {
  return (
    <section
      className="relative min-h-screen overflow-hidden flex flex-col"
      style={{ background: "${content.bgColor}" }}
    >
      <${componentName}
        color="${config.color}"
        opacity={${config.opacity}}
        speed={${config.speed}}
        size={${config.size}}
      />
      <div
        className="absolute inset-0"
        style={{ background: "${content.overlayTint}${Math.round(content.overlayDarkness * 255).toString(16).padStart(2, "0")}" }}
      />
      <nav className="relative z-10 flex items-center justify-between px-8 md:px-12 py-5">
        <span className="text-xs tracking-widest text-white/60">${content.brand}</span>
        <div className="flex gap-6 text-xs text-white/30">
          <a href="#">Product</a>
          <a href="#">Docs</a>
          <a href="#">Pricing</a>
        </div>
      </nav>
      <div className="relative z-10 flex-1 flex items-center px-8 md:px-12 py-20">
        <div className="max-w-2xl">
          <h1 className="text-5xl md:text-6xl font-light tracking-tight text-white leading-tight mb-5">
            ${content.headline.replace(/\n/g, "\\n")}
          </h1>
          <p className="text-sm text-white/50 mb-8 max-w-md leading-relaxed">
            ${content.subheadline}
          </p>
          <div className="flex items-center gap-3 flex-wrap">
            <button className="bg-white text-neutral-950 px-6 py-3 text-xs tracking-widest font-semibold hover:bg-white/90 transition-colors">
              ${content.cta}
            </button>
            <button className="border border-white/20 text-white/60 px-6 py-3 text-xs tracking-widest hover:border-white/40 transition-colors">
              ${content.ctaSecondary}
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}`
}
