"use client"

import { useState } from "react"
import { Check, Copy } from "lucide-react"
import { useCopy } from "@/hooks/useCopy"
import { HeroContent, HeroLayout } from "./HeroPrototype"
import { PatternConfig } from "@/types"

interface Props {
  tsx: string
  css: string
  patternId: string
  patternName: string
  config: PatternConfig
  content: HeroContent
}

type Tab = "tsx" | "css" | "section"

function generateFullSection(patternName: string, config: PatternConfig, content: HeroContent): string {
  const componentName = patternName.replace(/\s/g, "")
  const layoutComments: Record<HeroLayout, string> = {
    left:     "// Left-aligned SaaS layout (Linear / Vercel style)",
    centered: "// Centered layout (agency / portfolio style)",
    split:    "// Split layout (text + UI card)",
    minimal:  "// Minimal / brutalist layout",
  }

  return `"use client"

import { ${componentName} } from "@/components/patterns/${componentName}"

${layoutComments[content.layout]}
// Generated by bglab.dev — free animated background patterns

export function HeroSection() {
  return (
    <section
      className="relative min-h-screen overflow-hidden flex flex-col"
      style={{ background: "${content.bgColor}" }}
    >
      {/* Animated background pattern */}
      <${componentName}
        color="${config.color}"
        opacity={${config.opacity}}
        speed={${config.speed}}
      />

      {/* Overlay */}
      <div
        className="absolute inset-0"
        style={{ background: "${content.overlayTint}${Math.round(content.overlayDarkness * 255).toString(16).padStart(2, "0")}" }}
      />

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between px-8 py-5">
        <span className="text-xs tracking-widest text-white/60">${content.brand}</span>
        <div className="flex gap-5 text-xs text-white/30">
          <a href="#">Product</a>
          <a href="#">Docs</a>
          <a href="#">Pricing</a>
        </div>
      </nav>

      {/* Hero content */}
      <div className="relative z-10 flex-1 flex items-center px-8 py-20">
        <div className="max-w-2xl">
          <h1 className="text-5xl font-light tracking-tight text-white leading-tight mb-4">
            ${content.headline.replace(/\n/g, "\\n")}
          </h1>
          <p className="text-sm text-white/50 mb-8 max-w-md">
            ${content.subheadline}
          </p>
          <div className="flex items-center gap-3">
            <button className="bg-white text-neutral-950 px-5 py-2.5 text-xs tracking-widest font-medium hover:bg-white/90 transition-colors">
              ${content.cta}
            </button>
            <button className="border border-white/20 text-white/60 px-5 py-2.5 text-xs tracking-widest hover:border-white/40 transition-colors">
              ${content.ctaSecondary}
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}`
}

export function CodePanel({ tsx, css, patternName, config, content }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>("tsx")
  const { copy, copied } = useCopy()

  const code = {
    tsx,
    css,
    section: generateFullSection(patternName, config, content),
  }

  const activeCode = code[activeTab]

  const tabs: { id: Tab; label: string }[] = [
    { id: "tsx",     label: "REACT" },
    { id: "css",     label: "CSS" },
    { id: "section", label: "FULL SECTION" },
  ]

  return (
    <div className="flex flex-col h-full border border-white/10 bg-neutral-900/50">
      {/* Tab bar */}
      <div className="flex items-center justify-between border-b border-white/10 px-4 shrink-0">
        <div className="flex">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-3 py-3 text-[10px] tracking-widest transition-colors whitespace-nowrap ${
                activeTab === tab.id
                  ? "text-white border-b border-white"
                  : "text-white/30 hover:text-white/60"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <button
          onClick={() => copy(activeCode)}
          className="flex items-center gap-1.5 text-xs text-white/40 hover:text-white transition-colors py-2 shrink-0 ml-2"
        >
          {copied ? (
            <><Check size={11} className="text-green-400" /><span className="text-green-400 text-[10px]">Copied!</span></>
          ) : (
            <><Copy size={11} /><span className="text-[10px]">Copy</span></>
          )}
        </button>
      </div>

      {/* Tab description */}
      {activeTab === "section" && (
        <div className="px-4 py-2 border-b border-white/5 bg-white/[0.02] shrink-0">
          <p className="text-[10px] text-white/30">
            Complete hero section with your content — drop into any Next.js page
          </p>
        </div>
      )}

      {/* Code */}
      <div className="flex-1 overflow-auto">
        <pre className="p-4 text-xs leading-relaxed text-white/60 font-mono whitespace-pre-wrap break-all">
          <code>{activeCode}</code>
        </pre>
      </div>
    </div>
  )
}
